# Each pick: (category, out_name, source, kind, params)
# kind: "copy" (original still), "loop" (start,end), "frame" (time)
R = "raw/"; V = "raw-video/"
BG = [
 ("bg-court-palm-noon-loop",   V+"Dau_JZFtM63_01.mp4",         "loop", (17.5, 24.3)),
 ("bg-court-dunk-day-loop",    V+"Da-pXFKNqn0_01.mp4",         "loop", (3.0, 11.0)),
 ("bg-court-night-arcade-loop",V+"DbIdA5FzcDL_01_dash1920.mp4","loop", (9.5, 17.5)),
 ("bg-court-blue-palms-loop",  V+"DavFZ9_NtR4_01.mp4",         "loop", (7.8, 13.9)),
 ("bg-run-cypress-loop",       V+"DasTsnyuDUT_01.mp4",         "loop", (15.0, 22.0)),
 ("bg-portrait-jersey-night",  R+"DZdUwBwjtP-_01.jpg", "copy", None),
 ("bg-portrait-sky-lowangle",  R+"DZdUwBwjtP-_15.jpg", "copy", None),
 ("bg-berlin-museum-island",   R+"DZdUwBwjtP-_14.jpg", "copy", None),
 ("bg-trail-overlook",         R+"DZdYOO0jjnX_01.jpg", "copy", None),
 ("bg-park-sunset",            R+"Cz90j6foHS6_01.jpg", "copy", None),
 ("bg-albania-blue-eye",       R+"C9kUFYSpfVn_01.jpg", "copy", None),
 ("bg-albania-palm-sea",       R+"C9kUFYSpfVn_03.jpg", "copy", None),
 ("bg-3x3-arena-jumper",       R+"C9VqQiIoi3Q_03.jpg", "copy", None),
]
GALLERY = [
 ("gallery-jersey-night",      R+"DZdUwBwjtP-_01.jpg", "copy", None),
 ("gallery-sky-lowangle",      R+"DZdUwBwjtP-_15.jpg", "copy", None),
 ("gallery-red-mirror",        R+"DZdUwBwjtP-_10.jpg", "copy", None),
 ("gallery-elevator-mirror",   R+"DZdUwBwjtP-_05.jpg", "copy", None),
 ("gallery-gym-glass-orange",  R+"DZdQT7pDqBC_07.jpg", "copy", None),
 ("gallery-dumpling-stand",    R+"DZdQT7pDqBC_05.jpg", "copy", None),
 ("gallery-dog-break",         R+"DZdQT7pDqBC_06.jpg", "copy", None),
 ("gallery-trail-overlook",    R+"DZdYOO0jjnX_01.jpg", "copy", None),
 ("gallery-albania-blue-eye",  R+"C9kUFYSpfVn_02.jpg", "copy", None),
 ("gallery-albania-beach",     R+"C9kUFYSpfVn_05.jpg", "copy", None),
 ("gallery-park-sunset",       R+"Cz90j6foHS6_01.jpg", "copy", None),
 ("gallery-3x3-layup",         R+"C9VqQiIoi3Q_02.jpg", "copy", None),
 ("gallery-3x3-jumper",        R+"C9VqQiIoi3Q_03.jpg", "copy", None),
 ("gallery-night-dunk",        V+"DbIdA5FzcDL_01_dash1920.mp4", "frame", 23.5),
 ("gallery-palm-court-jumper", V+"Dau_JZFtM63_01.mp4", "frame", 15.5),
]
MONTAGE = [
 ("montage-portrait-jersey-01",   R+"DZdUwBwjtP-_01.jpg", "copy", None),
 ("montage-portrait-sky-02",      R+"DZdUwBwjtP-_15.jpg", "copy", None),
 ("montage-portrait-red-mirror-03", R+"DZdUwBwjtP-_10.jpg", "copy", None),
 ("montage-portrait-elevator-04", R+"DZdUwBwjtP-_05.jpg", "copy", None),
 ("montage-portrait-beach-05",    R+"C9kUFYSpfVn_05.jpg", "copy", None),
 ("montage-city-tv-tower-06",     R+"DZdUwBwjtP-_14.jpg", "copy", None),
 ("montage-city-brandenburg-07",  R+"DZdUwBwjtP-_06.jpg", "copy", None),
 ("montage-city-trail-08",        R+"DZdYOO0jjnX_01.jpg", "copy", None),
 ("montage-work-dumplings-09",    R+"DZdQT7pDqBC_05.jpg", "copy", None),
 ("montage-work-code-10",         R+"Cz90j6foHS6_03.jpg", "copy", None),
 ("montage-gym-glass-orange-11",  R+"DZdQT7pDqBC_07.jpg", "copy", None),
 ("montage-gym-pullup-12",        V+"DbE_yguuupq_01.mp4", "frame", 23.0),
 ("montage-run-strava-13",        R+"DZdQT7pDqBC_01.jpg", "copy", None),
 ("montage-run-stride-14",        V+"DasTsnyuDUT_01.mp4", "frame", 7.5),
 ("montage-run-cypress-15",       V+"DasTsnyuDUT_01.mp4", "frame", 18.0),
 ("montage-court-3x3-drive-16",   R+"C9VqQiIoi3Q_01.jpg", "copy", None),
 ("montage-court-3x3-layup-17",   R+"C9VqQiIoi3Q_02.jpg", "copy", None),
 ("montage-court-3x3-jumper-18",  R+"C9VqQiIoi3Q_03.jpg", "copy", None),
 ("montage-court-night-dunk-19",  V+"DbIdA5FzcDL_01_dash1920.mp4", "frame", 7.5),
 ("montage-court-night-dunk-20",  V+"DbIdA5FzcDL_01_dash1920.mp4", "frame", 23.5),
 ("montage-court-boot-21",        V+"Dau_JZFtM63_01.mp4", "frame", 6.0),
 ("montage-court-palm-jumper-22", V+"Dau_JZFtM63_01.mp4", "frame", 15.5),
 ("montage-court-blue-shot-23",   V+"DavFZ9_NtR4_01.mp4", "frame", 0.5),
 ("montage-court-dunk-day-24",    V+"Da-pXFKNqn0_01.mp4", "frame", 31.5),
 ("montage-travel-blue-eye-25",   R+"C9kUFYSpfVn_02.jpg", "copy", None),
 ("montage-travel-parasols-26",   R+"C9kUFYSpfVn_04.jpg", "copy", None),
 ("montage-travel-palm-sea-27",   R+"C9kUFYSpfVn_03.jpg", "copy", None),
 ("montage-travel-night-beach-28",R+"C9kUFYSpfVn_06.jpg", "copy", None),
 ("montage-travel-beach-kick-29", V+"Dau3yLctma0_01.mp4", "frame", 20.0),
 ("montage-sunset-park-30",       R+"Cz90j6foHS6_01.jpg", "copy", None),
 ("montage-dog-31",               R+"DZdQT7pDqBC_06.jpg", "copy", None),
]
